[package]
name = "lemurs"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = { version = "0.16.0", features = [ "crossterm" ] }
bitflags = "1.3"
cassowary = "0.3"
unicode-segmentation = "1.2"
unicode-width = "0.1"
crossterm = { version = "0.22" }
serde = { version = "1", features = ["derive"]}
argh = "0.1"
pam = "0.7.0"
pgs-files = "0.0.7"
simple-signal = "1.1.0"
log = "0.4.0"
fern = "0.5.2"
chvt = "0.2.0"
rand = "0.8.4"
chrono = "0.4"
nix = "0.23.1"
