[package]
name = "lemurs"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = { version = "0.16.0", features = [ "crossterm" ] }
unicode-width = "0.1"
crossterm = { version = "0.22" }
pam = "0.7.0"
pgs-files = "0.0.7"
log = "0.4.0"
fern = "0.5.2"
chvt = "0.2.0"
rand = "0.8.4"
chrono = "0.4"
nix = "0.23.1"
logind-dbus = "0.1.1"
