[package]
name = "lemurs"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = { version = "0.16.0", features = [ "crossterm" ] }
bitflags = "1.3"
cassowary = "0.3"
unicode-segmentation = "1.2"
unicode-width = "0.1"
crossterm = { version = "0.22" }
serde = { version = "1", features = ["derive"]}
rand = "0.8"
argh = "0.1"
